server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /letsencrypt;
        try_files $uri =404;
        allow all;
    }

    location = /health {
        access_log off;
        return 200 'Healthy';
    }

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name ananyahospital.com www.ananyahospital.com;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/ananyahospital.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ananyahospital.com/privkey.pem;
    
    # SSL Optimization
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    
    # Security Headers
    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    
    location = / {
        try_files $uri $uri/ /index.html;
    }
    
    location = /health {
        access_log off;
        return 200 'Healthy';
    }
    
    error_page 404 /index.html;
    error_page 500 502 503 504 /index.html;
}